services:
  - type: web
    name: fluxo-backend
    env: docker
    plan: free
    # Indica a Render que el contexto de construcci√≥n es la carpeta backend
    rootDir: .
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
