services:
  - type: web
    name: fluxo-backend
    env: docker
    plan: free
    # Indica a Render que el Dockerfile est√° en la carpeta backend/
    dockerContext: backend/
    envVars:
      - key: PORT
        value: 10000
